const PageDta = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "retail",
    category: "smartphones",
    thumbnail: "/portfolio/tem01.jpg",
    logo: "/Clients_logo/Picture01.png",
    link: "https://ganacherybd.com/",
  },
  {
    id: 2,
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: "retail",
    category: "smartphones",
    thumbnail: "/portfolio/tem02.jpg",
    logo: "/Clients_logo/insignia.png",
    link: "https://insignia-resorts.com/",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: "retail",
    category: "smartphones",    
    thumbnail: "/portfolio/tem03.jpg",
    logo: "/Clients_logo/Picture8.png",
    link: "",
  },
  {
    id: 4,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "retail",
    category: "smartphones",
    thumbnail: "/portfolio/tem04.jpg",
    logo: "/Clients_logo/ifad.png",
    link: "https://ifadgroup.com/",
  },
  {
    id: 5,
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: "retail",
    category: "smartphones",
    thumbnail: "/portfolio/tem05.jpg",
    logo: "/Clients_logo/ifad.png",
    link: "https://ifadautos.com/",
  },
  {
    id: 6,
    title: "MacBook Pro",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: "retail",
    category: "laptops",
    thumbnail: "/portfolio/tem06.jpg",
    logo: "/Clients_logo/ifad.png",
    link: "https://www.ifadmultiproducts.com/",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "NGO",
    category: "laptops",
    thumbnail: "/portfolio/haefa.png",
    logo: "/Clients_logo/haefa.png",
    link: "https://haefa.org/",
  },
  {
    id: 8,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "sports",
    category: "laptops",
    thumbnail: "/portfolio/Bcb.jpeg",
    logo: "/Clients_logo/bcb.png",
    link: "https://www.tigercricket.com.bd/",
  },
  {
    id: 9,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "retail",
    category: "laptops",
    thumbnail: "/portfolio/tangonTravel.PNG",
    logo: "/Clients_logo/tangontravels.png",
    link: "http://tangon.biz/",
  },
  {
    id: 10,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "retail",
    category: "laptops",
    thumbnail: "/portfolio/muslinsahitto.PNG",
    logo: "/Clients_logo/muslim.png",
    link: "http://muslimsahityasangsad.com/",
  },
 
  {
    id: 12,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "retail",
    category: "laptops",
    thumbnail: "/portfolio/travelworld.PNG",
    logo: "/Clients_logo/travelworld.png",
    link: "https://ttw.com.bd/",
  },
  {
    id: 13,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "retail",
    category: "laptops",
    thumbnail: "/portfolio/uttaraclub.PNG",
    logo: "/Clients_logo/uttaraclub.png",
    link: "https://www.ucl.com.bd/",
  },
  
  
 
];

export default PageDta;
